version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: warehouse_password
      MYSQL_DATABASE: warehouse
      MYSQL_USER: warehouse_admin
      MYSQL_PASSWORD: warehouse_admin_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/warehouse?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: warehouse_admin
      SPRING_DATASOURCE_PASSWORD: warehouse_admin_password
volumes:
  dbdata: